/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab10_Java10Strategy2 */

#ifndef _Included_lab10_Java10Strategy2
#define _Included_lab10_Java10Strategy2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab10_Java10Strategy2
 * Method:    generateAnotherMoveInTheGame
 * Signature: ([IIII)I
 */
JNIEXPORT jint JNICALL Java_lab10_Java10Strategy2_generateAnotherMoveInTheGame
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
